TARGET_NATIVE_BRIDGE_ARCH := arm64
TARGET_NATIVE_BRIDGE_ARCH_VARIANT := armv8-a
TARGET_NATIVE_BRIDGE_CPU_VARIANT := generic
TARGET_NATIVE_BRIDGE_ABI := arm64-v8a

SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += device/x86_64-extras/ndk_translation/sepolicy/private

# FIXME
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
